# docker-compose up > Comando para subir um dockers
# docker ps > Mostrar quais containers estão rodando
# docker ps -a > Mostrar quais containers existem
# docker-compose up -d > sobe o docker, mas deixa o terminal livre
# docker container stop (primeiros 3 caracteres do id) > Parar um docker
# docker conatiner start (primeiros 3 caracteres do id) > subir container

version: '3.9'
services:
  mysql_container:
    env_file:
      - .env
    container_name: mysql_container
    hostname: mysql_container
    image: mysql:8
    restart: always
    command:
      - --authentication-policy=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    volumes:
      - ./mysql_container:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      TZ: America/Sao_Paulo